version: '3'
services:
  app:
    environment:
      - PORT=${PORT}
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=${DATABASE_PORT}
    build: 
      dockerfile: dev.Dockerfile
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          memory: '1000M'
        reservations:
          memory: '500M'