# docker-compose.yml

version: '3'
services:
  app:
    build: 
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    environment:
      -  DATABASE_HOST=host.docker.internal
      -  DATABASE_PORT=3306
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    deploy:
      resources:
        limits:
          memory: '1g'
        reservations:
          memory: '256M'